macro(build_mlpack install_prefix staging_prefix  )

  if(CMAKE_EXTRA_GENERATOR)
    set(CMAKE_GEN "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
  else()
    set(CMAKE_GEN "${CMAKE_GENERATOR}")
  endif()
  
  set(CMAKE_OSX_EXTERNAL_PROJECT_ARGS)
  if(APPLE)
    list(APPEND CMAKE_OSX_EXTERNAL_PROJECT_ARGS
      -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES}
      -DCMAKE_OSX_SYSROOT:STRING=${CMAKE_OSX_SYSROOT}
      -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
    )
  endif()

  set_property(DIRECTORY PROPERTY EP_STEP_TARGETS configure build test)

  SET(EXT_CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
  SET(EXT_CMAKE_C_FLAGS_RELEASE   ${CMAKE_C_FLAGS_RELEASE})
  
  SET(EXT_CMAKE_CXX_FLAGS_DEBUG   ${CMAKE_CXX_FLAGS_DEBUG})
  SET(EXT_CMAKE_C_FLAGS_DEBUG     ${CMAKE_C_FLAGS_DEBUG})
  
  SET(EXT_CMAKE_CXX_FLAGS "-fPIC ${CMAKE_CXX_FLAGS} -I${OpenBLAS_INCLUDE_DIRS}")
  SET(EXT_CMAKE_C_FLAGS   "-fPIC ${CMAKE_C_FLAGS}   -I${OpenBLAS_INCLUDE_DIRS}")
  
  SET(EXT_CMAKE_EXE_LINKER_FLAGS    ${CMAKE_EXE_LINKER_FLAGS})
  SET(EXT_CMAKE_MODULE_LINKER_FLAGS ${CMAKE_MODULE_LINKER_FLAGS})
  SET(EXT_CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS})
  
  message("BOOST_DIR=${BOOST_DIR}")
  message("OpenBLAS_LIBRARY=${OpenBLAS_LIBRARY}")
  
ExternalProject_Add(MLPACK
  URL "http://www.mlpack.org/files/mlpack-2.0.2.tar.gz"
  URL_MD5 "1f4dec7228954309f99363c76e6e0cfe"
  SOURCE_DIR MLPACK
  BINARY_DIR MLPACK-build
  CMAKE_GENERATOR ${CMAKE_GEN}
  CMAKE_ARGS
      -DBUILD_TESTING:BOOL=ON #${BUILD_TESTING}
      -DBUILD_CLI_EXECUTABLES:BOOL=OFF
      -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
      -DBUILD_SHARED_LIBS:BOOL=OFF
      -DCMAKE_SKIP_RPATH:BOOL=OFF
      -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
      -DMACOSX_RPATH:BOOL=ON
      -DCMAKE_INSTALL_RPATH:PATH=${install_prefix}/lib${LIB_SUFFIX}
      -DCMAKE_INSTALL_PREFIX:PATH=${install_prefix}
      -DARMADILLO_INCLUDE_DIR:PATH=${ARMADILLO_INCLUDE_DIR}
      -DARMADILLO_LIBRARY:FILEPATH=${ARMADILLO_LIBRARY}
      -DBoost_DIR:PATH=${BOOST_DIR}
      -DBOOST_ROOT:PATH=${BOOST_DIR}
      ${CMAKE_OSX_EXTERNAL_PROJECT_ARGS}
      "-DCMAKE_CXX_FLAGS_RELEASE:STRING=${EXT_CMAKE_CXX_FLAGS_RELEASE}"
      "-DCMAKE_C_FLAGS_RELEASE:STRING=${EXT_CMAKE_C_FLAGS_RELEASE}"
      "-DCMAKE_CXX_FLAGS_DEBUG:STRING=${EXT_CMAKE_CXX_FLAGS_DEBUG}"
      "-DCMAKE_C_FLAGS_DEBUG:STRING=${EXT_CMAKE_C_FLAGS_DEBUG}"
      "-DCMAKE_CXX_FLAGS:STRING=${EXT_CMAKE_CXX_FLAGS}"
      "-DCMAKE_C_FLAGS:STRING=${EXT_CMAKE_C_FLAGS}"
      "-DCMAKE_EXE_LINKER_FLAGS:STRING=${EXT_CMAKE_EXE_LINKER_FLAGS}"
      "-DCMAKE_MODULE_LINKER_FLAGS:STRING=${EXT_CMAKE_MODULE_LINKER_FLAGS}"
      "-DCMAKE_SHARED_LINKER_FLAGS:STRING=${EXT_CMAKE_SHARED_LINKER_FLAGS}"
      -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
      -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
  INSTALL_COMMAND $(MAKE) install DESTDIR=${staging_prefix}
  INSTALL_DIR ${staging_prefix}/${install_prefix}
#  TEST_COMMAND make test
)

SET(MLPACK_INCLUDE_DIR ${staging_prefix}/${install_prefix}/include )
SET(MLPACK_LIBRARY_DIR ${staging_prefix}/${install_prefix}/lib${LIB_SUFFIX} )
SET(MLPACK_LIBRARY     ${staging_prefix}/${install_prefix}/lib${LIB_SUFFIX}/libmlpack.a )
SET(MLPACK_FOUND ON)
endmacro(build_mlpack)
