macro(build_armadillo install_prefix staging_prefix  )

  if(CMAKE_EXTRA_GENERATOR)
    set(CMAKE_GEN "${CMAKE_EXTRA_GENERATOR} - ${CMAKE_GENERATOR}")
  else()
    set(CMAKE_GEN "${CMAKE_GENERATOR}")
  endif()
  
  set(CMAKE_OSX_EXTERNAL_PROJECT_ARGS)
  if(APPLE)
    list(APPEND CMAKE_OSX_EXTERNAL_PROJECT_ARGS
      -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES}
      -DCMAKE_OSX_SYSROOT:STRING=${CMAKE_OSX_SYSROOT}
      -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${CMAKE_OSX_DEPLOYMENT_TARGET}
    )
  endif()

  set_property(DIRECTORY PROPERTY EP_STEP_TARGETS configure build test)

  SET(EXT_CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
  SET(EXT_CMAKE_C_FLAGS_RELEASE   ${CMAKE_C_FLAGS_RELEASE})
  
  SET(EXT_CMAKE_CXX_FLAGS_DEBUG   ${CMAKE_CXX_FLAGS_DEBUG})
  SET(EXT_CMAKE_C_FLAGS_DEBUG     ${CMAKE_C_FLAGS_DEBUG})
  
  SET(EXT_CMAKE_CXX_FLAGS "-fPIC ${CMAKE_CXX_FLAGS}")
  SET(EXT_CMAKE_C_FLAGS   "-fPIC ${CMAKE_C_FLAGS}")
  
ExternalProject_Add(ARMADILLO
  URL "http://sourceforge.net/projects/arma/files/armadillo-6.600.4.tar.gz"
  URL_MD5 "bdd3a34aa9a350a2add53329118cb415"
  SOURCE_DIR ARMADILLO
  BINARY_DIR ARMADILLO-build
  CMAKE_GENERATOR ${CMAKE_GEN}
  CMAKE_ARGS
      -DBUILD_TESTING:BOOL=ON #${BUILD_TESTING}
      -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
      -DBUILD_SHARED_LIBS:BOOL=ON
      -DCMAKE_SKIP_RPATH:BOOL=OFF
      -DCMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
      -DMACOSX_RPATH:BOOL=ON
      -DCMAKE_INSTALL_RPATH:PATH=${install_prefix}/lib${LIB_SUFFIX}
      -DCMAKE_INSTALL_PREFIX:PATH=${install_prefix}
      ${CMAKE_OSX_EXTERNAL_PROJECT_ARGS}
      "-DCMAKE_CXX_FLAGS_RELEASE:STRING=${EXT_CMAKE_CXX_FLAGS_RELEASE}"
      "-DCMAKE_C_FLAGS_RELEASE:STRING=${EXT_CMAKE_C_FLAGS_RELEASE}"
      "-DCMAKE_CXX_FLAGS_DEBUG:STRING=${EXT_CMAKE_CXX_FLAGS_DEBUG}"
      "-DCMAKE_C_FLAGS_DEBUG:STRING=${EXT_CMAKE_C_FLAGS_DEBUG}"
      "-DCMAKE_CXX_FLAGS:STRING=${EXT_CMAKE_CXX_FLAGS}"
      "-DCMAKE_C_FLAGS:STRING=${EXT_CMAKE_C_FLAGS}"
      -DCMAKE_EXE_LINKER_FLAGS:STRING=${CMAKE_EXE_LINKER_FLAGS}
      -DCMAKE_MODULE_LINKER_FLAGS:STRING=${CMAKE_MODULE_LINKER_FLAGS}
      -DCMAKE_SHARED_LINKER_FLAGS:STRING=${CMAKE_SHARED_LINKER_FLAGS}
      -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
      -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
      -Dopenblas_LIBRARY:FILEPATH=${OpenBLAS_LIBRARY}
      -DATLAS_CBLAS_INCLUDE_DIR:PATH=${OpenBLAS_INCLUDE_DIRS}
      -DATLAS_CLAPACK_INCLUDE_DIR:PATH=${OpenBLAS_INCLUDE_DIRS}
      -DBLAS_LIBRARY:FILEPATH=${OpenBLAS_LIBRARY}
      -DLAPACK_LIBRARY:FILEPATH=${OpenBLAS_LIBRARY}
      
  INSTALL_COMMAND $(MAKE) install DESTDIR=${staging_prefix}
  INSTALL_DIR ${staging_prefix}/${install_prefix}
#  TEST_COMMAND make test
)

SET(ARMADILLO_INCLUDE_DIR ${staging_prefix}/${install_prefix}/include )
SET(ARMADILLO_LIBRARY_DIR ${staging_prefix}/${install_prefix}/lib${LIB_SUFFIX} )
SET(ARMADILLO_LIBRARY     ${staging_prefix}/${install_prefix}/lib${LIB_SUFFIX}/libarmadillo.so )
SET(ARMADILLO_FOUND ON)

endmacro(build_armadillo)
